/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CustomerOrderInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5629423291365940948L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerOrderInfo\",\"namespace\":\"avro\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",\"string\"]},{\"name\":\"email\",\"type\":[\"null\",\"string\"]},{\"name\":\"phone\",\"type\":[\"null\",\"string\"]},{\"name\":\"ssn\",\"type\":[\"null\",\"string\"]},{\"name\":\"orderList\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Order\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"]},{\"name\":\"ssn\",\"type\":[\"null\",\"string\"]},{\"name\":\"orderDate\",\"type\":[\"null\",\"string\"]},{\"name\":\"orderValue\",\"type\":[\"null\",\"string\"]}]}}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CustomerOrderInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CustomerOrderInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CustomerOrderInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CustomerOrderInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CustomerOrderInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CustomerOrderInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CustomerOrderInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CustomerOrderInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CustomerOrderInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence name;
  private java.lang.CharSequence email;
  private java.lang.CharSequence phone;
  private java.lang.CharSequence ssn;
  private java.util.List<avro.Order> orderList;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CustomerOrderInfo() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param email The new value for email
   * @param phone The new value for phone
   * @param ssn The new value for ssn
   * @param orderList The new value for orderList
   */
  public CustomerOrderInfo(java.lang.CharSequence name, java.lang.CharSequence email, java.lang.CharSequence phone, java.lang.CharSequence ssn, java.util.List<avro.Order> orderList) {
    this.name = name;
    this.email = email;
    this.phone = phone;
    this.ssn = ssn;
    this.orderList = orderList;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return email;
    case 2: return phone;
    case 3: return ssn;
    case 4: return orderList;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: email = (java.lang.CharSequence)value$; break;
    case 2: phone = (java.lang.CharSequence)value$; break;
    case 3: ssn = (java.lang.CharSequence)value$; break;
    case 4: orderList = (java.util.List<avro.Order>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'phone' field.
   * @return The value of the 'phone' field.
   */
  public java.lang.CharSequence getPhone() {
    return phone;
  }


  /**
   * Sets the value of the 'phone' field.
   * @param value the value to set.
   */
  public void setPhone(java.lang.CharSequence value) {
    this.phone = value;
  }

  /**
   * Gets the value of the 'ssn' field.
   * @return The value of the 'ssn' field.
   */
  public java.lang.CharSequence getSsn() {
    return ssn;
  }


  /**
   * Sets the value of the 'ssn' field.
   * @param value the value to set.
   */
  public void setSsn(java.lang.CharSequence value) {
    this.ssn = value;
  }

  /**
   * Gets the value of the 'orderList' field.
   * @return The value of the 'orderList' field.
   */
  public java.util.List<avro.Order> getOrderList() {
    return orderList;
  }


  /**
   * Sets the value of the 'orderList' field.
   * @param value the value to set.
   */
  public void setOrderList(java.util.List<avro.Order> value) {
    this.orderList = value;
  }

  /**
   * Creates a new CustomerOrderInfo RecordBuilder.
   * @return A new CustomerOrderInfo RecordBuilder
   */
  public static avro.CustomerOrderInfo.Builder newBuilder() {
    return new avro.CustomerOrderInfo.Builder();
  }

  /**
   * Creates a new CustomerOrderInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CustomerOrderInfo RecordBuilder
   */
  public static avro.CustomerOrderInfo.Builder newBuilder(avro.CustomerOrderInfo.Builder other) {
    if (other == null) {
      return new avro.CustomerOrderInfo.Builder();
    } else {
      return new avro.CustomerOrderInfo.Builder(other);
    }
  }

  /**
   * Creates a new CustomerOrderInfo RecordBuilder by copying an existing CustomerOrderInfo instance.
   * @param other The existing instance to copy.
   * @return A new CustomerOrderInfo RecordBuilder
   */
  public static avro.CustomerOrderInfo.Builder newBuilder(avro.CustomerOrderInfo other) {
    if (other == null) {
      return new avro.CustomerOrderInfo.Builder();
    } else {
      return new avro.CustomerOrderInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for CustomerOrderInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerOrderInfo>
    implements org.apache.avro.data.RecordBuilder<CustomerOrderInfo> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence email;
    private java.lang.CharSequence phone;
    private java.lang.CharSequence ssn;
    private java.util.List<avro.Order> orderList;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.CustomerOrderInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.phone)) {
        this.phone = data().deepCopy(fields()[2].schema(), other.phone);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.ssn)) {
        this.ssn = data().deepCopy(fields()[3].schema(), other.ssn);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.orderList)) {
        this.orderList = data().deepCopy(fields()[4].schema(), other.orderList);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing CustomerOrderInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.CustomerOrderInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.phone)) {
        this.phone = data().deepCopy(fields()[2].schema(), other.phone);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ssn)) {
        this.ssn = data().deepCopy(fields()[3].schema(), other.ssn);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.orderList)) {
        this.orderList = data().deepCopy(fields()[4].schema(), other.orderList);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public avro.CustomerOrderInfo.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public avro.CustomerOrderInfo.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public avro.CustomerOrderInfo.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.email = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public avro.CustomerOrderInfo.Builder clearEmail() {
      email = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'phone' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhone() {
      return phone;
    }


    /**
      * Sets the value of the 'phone' field.
      * @param value The value of 'phone'.
      * @return This builder.
      */
    public avro.CustomerOrderInfo.Builder setPhone(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.phone = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'phone' field has been set.
      * @return True if the 'phone' field has been set, false otherwise.
      */
    public boolean hasPhone() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'phone' field.
      * @return This builder.
      */
    public avro.CustomerOrderInfo.Builder clearPhone() {
      phone = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ssn' field.
      * @return The value.
      */
    public java.lang.CharSequence getSsn() {
      return ssn;
    }


    /**
      * Sets the value of the 'ssn' field.
      * @param value The value of 'ssn'.
      * @return This builder.
      */
    public avro.CustomerOrderInfo.Builder setSsn(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.ssn = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ssn' field has been set.
      * @return True if the 'ssn' field has been set, false otherwise.
      */
    public boolean hasSsn() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ssn' field.
      * @return This builder.
      */
    public avro.CustomerOrderInfo.Builder clearSsn() {
      ssn = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderList' field.
      * @return The value.
      */
    public java.util.List<avro.Order> getOrderList() {
      return orderList;
    }


    /**
      * Sets the value of the 'orderList' field.
      * @param value The value of 'orderList'.
      * @return This builder.
      */
    public avro.CustomerOrderInfo.Builder setOrderList(java.util.List<avro.Order> value) {
      validate(fields()[4], value);
      this.orderList = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'orderList' field has been set.
      * @return True if the 'orderList' field has been set, false otherwise.
      */
    public boolean hasOrderList() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'orderList' field.
      * @return This builder.
      */
    public avro.CustomerOrderInfo.Builder clearOrderList() {
      orderList = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CustomerOrderInfo build() {
      try {
        CustomerOrderInfo record = new CustomerOrderInfo();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.email = fieldSetFlags()[1] ? this.email : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.phone = fieldSetFlags()[2] ? this.phone : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ssn = fieldSetFlags()[3] ? this.ssn : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.orderList = fieldSetFlags()[4] ? this.orderList : (java.util.List<avro.Order>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CustomerOrderInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<CustomerOrderInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CustomerOrderInfo>
    READER$ = (org.apache.avro.io.DatumReader<CustomerOrderInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.name);
    }

    if (this.email == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.email);
    }

    if (this.phone == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.phone);
    }

    if (this.ssn == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.ssn);
    }

    if (this.orderList == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.orderList.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (avro.Order e0: this.orderList) {
        actualSize0++;
        out.startItem();
        e0.customEncode(out);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.name = null;
      } else {
        this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.email = null;
      } else {
        this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.phone = null;
      } else {
        this.phone = in.readString(this.phone instanceof Utf8 ? (Utf8)this.phone : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.ssn = null;
      } else {
        this.ssn = in.readString(this.ssn instanceof Utf8 ? (Utf8)this.ssn : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.orderList = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<avro.Order> a0 = this.orderList;
        if (a0 == null) {
          a0 = new SpecificData.Array<avro.Order>((int)size0, SCHEMA$.getField("orderList").schema().getTypes().get(1));
          this.orderList = a0;
        } else a0.clear();
        SpecificData.Array<avro.Order> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<avro.Order>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            avro.Order e0 = (ga0 != null ? ga0.peek() : null);
            if (e0 == null) {
              e0 = new avro.Order();
            }
            e0.customDecode(in);
            a0.add(e0);
          }
        }
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.name = null;
          } else {
            this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.email = null;
          } else {
            this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.phone = null;
          } else {
            this.phone = in.readString(this.phone instanceof Utf8 ? (Utf8)this.phone : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.ssn = null;
          } else {
            this.ssn = in.readString(this.ssn instanceof Utf8 ? (Utf8)this.ssn : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.orderList = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<avro.Order> a0 = this.orderList;
            if (a0 == null) {
              a0 = new SpecificData.Array<avro.Order>((int)size0, SCHEMA$.getField("orderList").schema().getTypes().get(1));
              this.orderList = a0;
            } else a0.clear();
            SpecificData.Array<avro.Order> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<avro.Order>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                avro.Order e0 = (ga0 != null ? ga0.peek() : null);
                if (e0 == null) {
                  e0 = new avro.Order();
                }
                e0.customDecode(in);
                a0.add(e0);
              }
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










